development:
  adapter: sqlite3
  encoding: utf8
  database: db/development.db

test:
  adapter: sqlite3
  encoding: utf8
  database: db/test.db

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
